ALTER TABLE users ADD COLUMN wins INT NOT NULL DEFAULT 0;
ALTER TABLE users ALTER wins DROP DEFAULT;

ALTER TABLE users ADD COLUMN losses INT NOT NULL DEFAULT 0;
ALTER TABLE users ALTER losses DROP DEFAULT;

ALTER TABLE users ADD COLUMN matches INT NOT NULL DEFAULT 0;
ALTER TABLE users ALTER matches DROP DEFAULT;

ALTER TABLE users ADD COLUMN tournaments INT NOT NULL DEFAULT 0;
ALTER TABLE users ALTER tournaments DROP DEFAULT;
